core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',
         authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('core:index')), name='logout'),
]

items/urls.py
from django.urls import path

from . import views

app_name = "items"

urlpatterns = [
    path('', views.items, name="items"),
    path("new/", views.new, name="new"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/edit/', views.edit, name="edit"),
    path('<int:pk>/delete/', views.delete, name="delete"),
]

listing/urls.py

from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('items.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),


]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class Item(models.Model):
    title = models.CharField(max_length=255, null=True)
    price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    location = models.CharField(max_length=50, null=True)
    created_at = models.DateField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

items/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

# Signup Form


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'Your username',
                'class': 'w-full py-4 px-6 rounded-xl',
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Your email address',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'password1': forms.PasswordInput(attrs={
                'placeholder': 'Your password',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
            'password2': forms.PasswordInput(attrs={
                'placeholder': 'Repeat password',
                'class': 'w-full py-4 px-6 rounded-xl'
            }),
        }

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your username',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

        email = forms.CharField(widget=forms.EmailInput(attrs={
            'placeholder': 'Your email address',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

        password1 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Your password',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

        password2 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Repeat password',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

# Login Form


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

items/forms.py
from django import forms

from core.models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border mb-3'


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('title', 'description', 'price', 'location')

        widgets = {
            'title': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'location': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),

        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('title', 'description', 'price', 'location')

        widgets = {
            'title': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'location': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

core/views.py
from django.shortcuts import render, redirect
from .models import Item
from .forms import SignUpForm


def index(request):
    items = Item.objects.all()
    ordered_items = items.order_by('-created_at')
    return render(request, 'core/index.html', {
        'items': ordered_items
    })


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')

    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {
        'form': form

    })

items/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from core.models import Item
from .forms import NewItemForm, EditItemForm


def items(request):
    query = request.GET.get('query', '')
    items = Item.objects.all()

    if query:
        items = items.filter(name__icontains=query)

    # Order the items by the created_at field in descending order (newest first)
    items = items.order_by('-created_at')

    return render(request, 'items/items.html', {
        'items': items,
        'query': query
    })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'items/detail.html', {'item': item})


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('items:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'items/form.html', {
        'form': form,
        'title': 'New item',
    })


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk)

    if request.method == 'POST':
        form = EditItemForm(request.POST, instance=item)

        if form.is_valid():
            form.save()

            return redirect('items:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'items/form.html', {
        'form': form,
        'title': 'Edit item',
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk)
    item.delete()

    return redirect('core:index')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listing</title>
</head>
<body>
    
</body>
</html>

core/templates/core/index.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>Listing API</title>
</head>
<body class="w-full max-w-6xl m-auto p-8">
    <nav class="mt-12 flex gap-x-5 items-center justify">
      {% if request.user.is_authenticated  %}
       <a href="{% url "items:new" %}" class="px-6 py-1 text-lg font-semibold bg-teal-800 text-white rounded-xl hover:bg-teal-700">Post item</a>
       <form action="{% url 'core:logout' %}" method="post" id="logout-form">
        {% csrf_token %}
        <a href="#" class="font-semibold underline text-blue-800" onclick="document.getElementById('logout-form').submit();">Logout</a>
        </form>
      {% else %}
        <a href="{% url "core:signup" %}" class="px-6 py-3 text-lg font-semibold bg-teal-800 text-white rounded-xl hover:bg-teal-700">Signup</a>
        <a href="{% url "core:login" %}" class="px-6 py-3 text-lg font-semibold bg-teal-800 text-white rounded-xl hover:bg-teal-700">Login</a>
      {% endif %}  
    </nav>
    {% if items|length == 0 %}
      <h3 class="text-3xl mt-3">No items to display, add new item</h3>
    {% else %}
      <h1 class="text-4xl my-6">Listing items: </h1>
      <div class="grid grid-cols-2 lg:grid-cols-4 gap-3 w-full max-w-[1100px] pb-16">
        {% for item in items %}    
          <div class="flex flex-col flex-1 border-2 border-slate-500 p-3 w-full max-w-[250px] rounded-md ">
            <div class="flex-1">
              <h3 class="text-lg font-semibold">{{ item.title }}</h3>
              <h4 class="text-slate-600">{{ item.description }}</h4>
              <h2 class="text-3xl text-slate-950 font-bold">{{ item.price }}</h2>
              <small class="text-slate-600">{{ item.location }}</small>
            </div>            
            <small class="text-slate-600">{{ item.created_at }}</small>
            <small class="text-slate-600">By: {{ item.created_by }}</small>
            <a href="{% url "items:detail" pk=item.pk %}" class="bg-gray-950 rounded-md mt-2 text-white p-3">See listing</a>
          </div>    
        {% endfor %}
      </div>
    {% endif %}
</body>
</html>

core/templates/core/login.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>Login</title>
</head>
<body>
    
</body>
</html>

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form action="." method="post">
        {% csrf_token %}       

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br/>
            {{ form.username }}
        </div>

        
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br/>
            {{ form.password }}
        </div>
      
        {% comment %} Handling errors {% endcomment %}
        {% if form.errors or form.non_field_errors%}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
            Submit
        </button>
    </form>
</div>
{% endblock  %}

core/templates/core/signup.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>Signup</title>
</head>
<body>
  
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form action="." method="post" class="w-full">
        {% csrf_token %}       

        <div class="mb-3">
            <label class="w-full inline-block mb-2">Username</label><br/>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="w-full inline-block mb-2">Email</label><br/>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="w-full inline-block mb-2">Password</label><br/>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="w-full inline-block mb-2">Repeat password</label><br/>
            {{ form.password2 }}
        </div>
        {% comment %} Handling errors {% endcomment %}
        {% if form.errors or form.non_field_errors%}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
            Submit
        </button>        
    </form>
    <span class="pt-5">Already have an account? <a href="{% url "core:login" %}" class="text-blue-400">Login</a></span>
</div>

</body>
</html>

items/templates/items/detail.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>{{ item.title }} - Listing API</title>
</head>
<body class="w-full max-w-6xl m-auto p-8">
    <div class="w-full max-w-[300px] border-2 border-gray-500 rounded-md p-3">

        
        <h1 class="text-4xl my-6">{{ item.title }}</h1>
        <p>{{ item.description }}</p>
        <p class="text-3xl">{{ item.price }}</p>
        <p>Location: {{ item.location }}</p>
        <p>Created at: {{ item.created_at }}</p>
        <div class="flex justify-between items-center">
            <small>By: {{ item.created_by }}</small>
            {% if request.user == item.created_by %}
            <a href="{% url 'items:delete' item.id %}" class="ms-12 bg-red-700 text-white px-3 py-1 rounded-md ">Delete</a>
            <a href="{% url 'items:edit' item.id %}" class="ms-12 bg-teal-700 text-white px-3 py-1 rounded-md ">Edit</a>
            {% endif %}
        </div>
        <br>
        <!-- Add any other details you want to display -->
        <a href="{% url 'core:index' %}" class="text-slate-500 mt-3 "><--Back to items</a>
    </div>
</body>
</html>

items/templates/items/form.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>New Item</title>
</head>
<body class="w-full max-w-6xl">
    {% block content %}
    <h1 class="mb-3 mt-2 text-4xl text-center ">{{ title }}</h1> 
        <form 
            action="."
            method="post" 
            enctype="multipart/form-data"
            class="px-6 w-full max-w-2xl  m-auto">
            {% csrf_token %}
    
            <div class="space-y-4">
                {{ form.as_p }}
            </div>

            {% comment %} Handling errors {% endcomment %}
            {% if form.errors or form.non_field_errors%}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        
        <button class="mt-3 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
            Submit
        </button>
        </form>
   
{% endblock  %}
</body>
</html>


theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>